package analysisView;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeView;

import java.net.URL;
import java.util.Map;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import main.DBProcessor;
import main.Road;
import main.User;

public class AnalysisRoadViewController implements Initializable{
	private Map<Integer, Road> allRoads;
	private DBProcessor dbProcessor = new DBProcessor();
	private User currentUser;
	@FXML
	private Label title;
	@FXML
	private Scene scene;
	@FXML
	private VBox sidebar;
	@FXML
	private Button searchViewBtn;
	@FXML
	private Button advSearchBtn;
	@FXML
	private Button btn2;
	@FXML
	private Button exitBtn;
	@FXML
	private TextField searchTF;
	@FXML
	private Button searchBtn;
	@FXML
	private VBox rootVBox;
	@FXML
	private VBox roadVBox;
	@FXML
	private HBox item;
	@FXML
	private Button itemAddBtn;
	@FXML
	private Label itemName;

	// Event Listener on Button[#advSearchBtn].onMouseClicked
	@FXML
	public void handleAdvSearchRoadViewBtn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#searchBtn].onAction
	@FXML
	public void handleSearchResult(ActionEvent event) {
		// TODO Autogenerated
	}

	public void initialize(URL location, ResourceBundle resources) {
		allRoads = dbProcessor.fetchRoad();		
		roadVBox = new VBox();
		itemName = new Label("滨江雅苑");
		itemAddBtn = new Button("全部添加");
		item = new HBox();
		item.getChildren().add(itemName);
		item.getChildren().add(itemAddBtn);
		roadVBox.getChildren().add(item);
		
		itemName = new Label("大华三路");
		itemAddBtn = new Button("添加");
		item = new HBox();
		item.getChildren().add(itemName);
		item.getChildren().add(itemAddBtn);
		roadVBox.getChildren().add(item);
		
		itemName = new Label("大华路");
		itemAddBtn = new Button("添加");
		item = new HBox();
		item.getChildren().add(itemName);
		item.getChildren().add(itemAddBtn);
		roadVBox.getChildren().add(item);
		
		rootVBox.getChildren().add(roadVBox);
		
	}
}
